spring:
  application:
    name: franchise-api
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}

server:
  forward-headers-strategy: framework
